name: responsive_design_helper
description: A Flutter package providing utilities for responsive design across different screen sizes.
version: 0.0.1
homepage: https://github.com/your_username/responsive_design_helper # Update this with your package's homepage

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
